apiVersion: v1
kind: Service
metadata:
  name: oikos-api
  namespace: oikos
  labels:
    app: oikos-api
spec:
  selector:
    app: oikos-api
  ports:
    - name: http
      port: 8000
      targetPort: http
